version: '3.8'

services:
  server:
    image: emmatblingx/email-server:latest
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    image: emmatblingx/email-php:latest
    volumes:
      - ./backend:/var/www/html:delegated
  # mysql:
  #   image: mysql:5.7
  #   env_file:
  #     - ./env/mysql.env
  composer:
    image: emmatblingx/email-composer:latest
    volumes:
      - ./backend:/var/www/html
  artisan:
    image: emmatblingx/email-php:latest
    volumes:
      - ./backend:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    stdin_open: true
    tty: true
  frontend:
    image: emmatblingx/email-frontend:latest
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 3000:3000
