version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./backend:/var/www/html:delegated
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./backend:/var/www/html
    stdin_open: true
    tty: true
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./backend:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    stdin_open: true
    tty: true
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 3000:3000
